# Data Types in Python and Numpy
Effective data-driven computation requires us to have a deep understanding of how data is stored and manipulated. This notebook covers outlines and contrasts on how arrays of data are handled in the Python itself, and how NumPy improves this. We are going to understand much of this throughout the numpy module, but right now, let's stress a little on the

Unlike statically typed language, python gives us the flexiblity of auto setting the value of variables in the code rather than typing the exact data-type of the same. This could be considered as one of the reasons why python is slower as compared to a compile type and statically typed language. Let's try to understand this using a simple code comparision with c.

/* C code */
int sum = 0;
for(int i=0; i<100; i++){
    sum += i;
}
This exact piece of code, when written in python, is as follows:

 #python
 result = 0
 for i in range(100):
     result += i
Looks neat, isn't it? This code is more easily readable than the c code as we don't have to explicitly mention the datatypes we are working with and we can also change them easily whenever required.

In [1]:
list = ["2", 2, 2., True]
[type(item) for item in list]

[str, int, float, bool]

**so we can see the single python list contains of multiple data-types.**

In [2]:
import numpy as np


In [3]:
# integer array:
a = np.array([3, 1, 4, 1, 5, 9, 6, 2, 5])
a

array([3, 1, 4, 1, 5, 9, 6, 2, 5])

In [4]:
a.dtype

dtype('int64')

In [6]:
a = np.array([3.14, 1, 5, 9, 6, 2, 5])
a

array([3.14, 1.  , 5.  , 9.  , 6.  , 2.  , 5.  ])

In [7]:
a.dtype

dtype('float64')

In [8]:
a = np.array([3.14, "1", 5, 9, 6, 2, 5])
a; a.dtype

dtype('<U32')

# What do we see? 
We can clearly see that whenever there are different data-types in a numpy array, rather than giving a mixed set of dtypes, it gives one singular datatype.



**Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists**


In [9]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [3, 1, 4]])

array([[3, 4, 5],
       [1, 2, 3],
       [4, 5, 6]])