# A speed comparision of numpy with native python
The question should rise after reading the above lines - Numpy restricts us from using different dtypes in a single list, then why are we still trying to learn about numpy? The answer to this is speed. The use of dynamic datatypes is one of the reasons why python becomes slower than other languages. This means it makes our code faster: way faster compared to native python. Don't believe me? have a look at it yourself.


In [2]:
%%time
a=[]
for i in range(int(le6)):
    a.append(i)

NameError: name 'le6' is not defined

In [3]:
a = np.array([3, 1, 4, 1, 5, 9, 6, 2, 5])
a

NameError: name 'np' is not defined

In [1]:
List = ["2", 2, 2., True]
[type(item) for item in List]



[str, int, float, bool]

In [2]:
import numpy as np


In [3]:
# integer array:
a = np.array([3, 1, 4, 1, 5, 9, 6, 2, 5])
a

array([3, 1, 4, 1, 5, 9, 6, 2, 5])

In [4]:
%%time
a=[]
for i in range(int(1e6)):
    a.append(i)
    

CPU times: user 108 ms, sys: 13.8 ms, total: 122 ms
Wall time: 121 ms


In [5]:
%%time
a = [i for i in range(int(1e6))]


CPU times: user 64.2 ms, sys: 20.5 ms, total: 84.7 ms
Wall time: 84.9 ms


In [6]:
%%time
a = np.arange(1e6)

CPU times: user 20 ms, sys: 13.4 ms, total: 33.4 ms
Wall time: 31.4 ms


**We can clearly see that in order to create a list of one million numbers, it takes about 250ms for a python list which is only 51.4 ms using numpy. Clearly there is a 5 times improvement in speed using numpy as compared to native python. So clearly from now onwards you must start using numpy wrapper.**

# Creating Arrays from Scratch
**We have seen the dtypes of numpy array and how it helps us carry out larger computation by reducing the execution time. But the next question should be: how should I create arrays using numpy now? This section is going to guide you through the process of creating faster array in numpy.**

In [7]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# Create a 2x3 floating-point array filled with ones
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# Create a 2x3 array filled with value of pi
np.full((2, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [12]:
# create an array filled with a linear sequence: a list of values o 
# starting at 0, ending at 50, stepping by 5
# (this is simmilar to the built-in range() function)
np.arange(0, 50, 5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
#create an array of three values evenly spaced between 2 and 3
np.linspace(2, 3, 3)

array([2. , 2.5, 3. ])

In [15]:
# create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.02488027, 0.67902823, 0.41101549],
       [0.6766037 , 0.28425963, 0.03674277],
       [0.62775732, 0.42149148, 0.65875264]])

In [16]:
# creat a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[1, 9, 8],
       [5, 2, 4],
       [1, 8, 1]])

In [17]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

NumPy Standard Data Types NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations. Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

 